spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/soir
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
      format_sql: true
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: myprojecttest995@gmail.com
    password: 1q2w3e4r!@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    activate:
      on-profile:

#logging:
#  level:
#    org.hibernate.SQL: debug



logging:
  file:
       name: logs/application.log
  level:
    org.thymeleaf: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.quartz.core: INFO
    org.h2.server.web: INFO

#
#logging:
#  file: logs/application.log
#  level:
#    org.thymeleaf: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.quartz.core: DEBUG
#    org.h2.server.web: DEBUG
#
#
#logging:
#  config: classpath:logback-spring.xml
#
