spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/soir
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      format_sql: true
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

logging:
  level:
    org.hibernate.SQL: debug


